### ISSUE TITLE
Multiple keys in URL using `&ck=BASE64`

### ISSUE THREAD

**Issue by MaZED-UP** [sharkiller/Reproductor-MPD-M3U8#1]
**Is your feature request related to a problem? Please describe.**
I can't play encrypted MPD videos with multiple keys using `&ck=BASE64`. It only supports one key in the URL.

**Describe the solution you'd like**
Add support for videos encrypted with multiple keys when using `&ck=BASE64` in the URL.

**Describe alternatives you've considered**
[Reproductor M3U8 - HLS + DASH Player](https://chrome.google.com/webstore/detail/reproductor-m3u8-hls-%20-da/lcipembjfkmeggpihdpdgnjildgniffl)

**Additional context**
None

**Comment by sharkiller** [comment]
@MaZED-UP you need to do it in the extension settings.  
you add one key as a CK parameter and the rest as in the setting.

Sadly this is a limitation on the player used, JWPlayer only accept 1 single set of clearkey.

The arrays of clearkeys you can set in the settings is a hack to force cks in the dash player used by JWPlayer. But only works if jwplayer try to play the content. If it fail or stop on jwplayer it never reach the dash core.

Maybe when I have time i will try to append the cks from parameter to the cks on the settings option.

![image](https://user-images.githubusercontent.com/712193/229241085-470ac9a7-5344-4d78-a155-8844ea585e9d.png)

I made this extension because it use a more powerful player, more customizable and less prone to playback problems.

**Comment by sharkiller** [comment]
@MaZED-UP dont know if you are still interested but latest version support directly what you asked in the first place.

https://github.com/sharkiller/Reproductor-MPD-M3U8/wiki/Par%C3%A1metros-de-URL#-formato-de-par%C3%A1metro-ckcadena-en-base64
