### ISSUE TITLE
IPTV playlist channels didn't work

### ISSUE THREAD

**Issue by pasq96** [sharkiller/Reproductor-MPD-M3U8#14]
**Describe the bug**
I've an error when I try to reproduce a free IPTV playlist that I use to watch Italian FTA channels (available on GitHub [here](https://github.com/Tundrak/IPTV-Italia)). 
I downloaded one of the IPTV playlist files and loaded it into the extension as a local file, it displays the channel list correctly but no link works and an error 'This video file cannot be played. (Code Error: 102630)".

![image](https://github.com/sharkiller/Reproductor-MPD-M3U8/assets/25122385/5d20d983-f59d-4f44-b378-b173a3a3d7e0)

**To Reproduce**
1. Go to IPTV playlist github repo and download an IPTV playlist
2. Load it into "Play local M3U lists" function
4. See error: no working channel

**Expected behavior**
I expect channels to be loaded correctly

**Screenshots**
See above

**Desktop:**
 - OS: Windows 11
 - Browser: Chrome, Edge
 - Version: Chrome: v120.0.6099.216, Edge: v120.0.2210.133

**Additional context**
No

**Comment by pasq96** [comment]
are there any updates?

**Comment by sharkiller** [comment]
you will need to modify the m3u to include `#KODIPROP:inputstream.adaptive.file_type=mpd` with the correct filetype used for the stream, like mpd or m3u8 [as explained in the wiki](https://github.com/sharkiller/Reproductor-MPD-M3U8/wiki/M3U-format#-force-video-format). 

I can't test it because that streams are region locked and each channel redirect to a mp4 video that said only available in italy.
